.TH "python/zio/__main__.py" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/zio/__main__.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzio\&.__main__\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzio\&.__main__\&.cli\fP (ctx)"
.br
.ti -1c
.RI "def \fBzio\&.__main__\&.peers\fP (\fBtimeout\fP, wait_for, pre_sleep, post_sleep, name, headers)"
.br
.ti -1c
.RI "def \fBzio\&.__main__\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
