.TH "python/zio/__main__.py" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/zio/__main__.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzio\&.__main__\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzio\&.__main__\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBzio\&.__main__\&.level\fP"
.br
.ti -1c
.RI "\fBzio\&.__main__\&.format\fP"
.br
.ti -1c
.RI "\fBzio\&.__main__\&.datefmt\fP"
.br
.ti -1c
.RI "\fBzio\&.__main__\&.log\fP = logging\&.getLogger('zio')"
.br
.ti -1c
.RI "\fBzio\&.__main__\&.cli\fP = click\&.CommandCollection(sources=[peers\&.cli, flow\&.cli, domo\&.cli])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
