.TH "/home/bviren/dev/zio/build/c4che/_cache.py" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/bviren/dev/zio/build/c4che/_cache.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fB_cache\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fB_cache\&.AR\fP = ['/usr/bin/ar']"
.br
.ti -1c
.RI "list \fB_cache\&.ARFLAGS\fP = ['rcs']"
.br
.ti -1c
.RI "string \fB_cache\&.BINDIR\fP = '/home/bviren/opt/zio/bin'"
.br
.ti -1c
.RI "tuple \fB_cache\&.CC_VERSION\fP = ('7', '4', '0')"
.br
.ti -1c
.RI "string \fB_cache\&.COMPILER_CXX\fP = 'g++'"
.br
.ti -1c
.RI "string \fB_cache\&.CPPPATH_ST\fP = '\-I%s'"
.br
.ti -1c
.RI "list \fB_cache\&.CXX\fP = ['/usr/bin/g++']"
.br
.ti -1c
.RI "list \fB_cache\&.CXXFLAGS\fP = ['\-std=c++17', '\-g', '\-O2']"
.br
.ti -1c
.RI "list \fB_cache\&.CXXFLAGS_MACBUNDLE\fP = ['\-fPIC']"
.br
.ti -1c
.RI "list \fB_cache\&.CXXFLAGS_cxxshlib\fP = ['\-fPIC']"
.br
.ti -1c
.RI "list \fB_cache\&.CXXLNK_SRC_F\fP = []"
.br
.ti -1c
.RI "list \fB_cache\&.CXXLNK_TGT_F\fP = ['\-o']"
.br
.ti -1c
.RI "string \fB_cache\&.CXX_NAME\fP = 'gcc'"
.br
.ti -1c
.RI "list \fB_cache\&.CXX_SRC_F\fP = []"
.br
.ti -1c
.RI "list \fB_cache\&.CXX_TGT_F\fP = ['\-c', '\-o']"
.br
.ti -1c
.RI "list \fB_cache\&.DEFINES\fP = ['HAVE_ZMQ=1', 'HAVE_CZMQ=1', 'HAVE_ZYRE=1']"
.br
.ti -1c
.RI "list \fB_cache\&.DEFINES_CZMQ\fP = ['CZMQ_BUILD_DRAFT_API=1', 'ZMQ_BUILD_DRAFT_API=1']"
.br
.ti -1c
.RI "string \fB_cache\&.DEFINES_ST\fP = '\-D%s'"
.br
.ti -1c
.RI "list \fB_cache\&.DEFINES_ZMQ\fP = ['ZMQ_BUILD_DRAFT_API=1']"
.br
.ti -1c
.RI "list \fB_cache\&.DEFINES_ZYRE\fP = ['ZYRE_BUILD_DRAFT_API=1', 'CZMQ_BUILD_DRAFT_API=1', 'ZMQ_BUILD_DRAFT_API=1']"
.br
.ti -1c
.RI "dictionary \fB_cache\&.DEFINE_COMMENTS\fP = {'HAVE_ZYRE': '', 'HAVE_CZMQ': '', 'HAVE_ZMQ': ''}"
.br
.ti -1c
.RI "string \fB_cache\&.DEST_BINFMT\fP = 'elf'"
.br
.ti -1c
.RI "string \fB_cache\&.DEST_CPU\fP = 'x86_64'"
.br
.ti -1c
.RI "string \fB_cache\&.DEST_OS\fP = 'linux'"
.br
.ti -1c
.RI "int \fB_cache\&.HAVE_CZMQ\fP = 1"
.br
.ti -1c
.RI "int \fB_cache\&.HAVE_ZMQ\fP = 1"
.br
.ti -1c
.RI "int \fB_cache\&.HAVE_ZYRE\fP = 1"
.br
.ti -1c
.RI "list \fB_cache\&.INCLUDES_CZMQ\fP = ['/home/bviren/opt/zmq/include', '/usr/include/uuid', '/usr/include/x86_64\-linux\-gnu']"
.br
.ti -1c
.RI "list \fB_cache\&.INCLUDES_ZMQ\fP = ['/home/bviren/opt/zmq/include']"
.br
.ti -1c
.RI "list \fB_cache\&.INCLUDES_ZYRE\fP = ['/home/bviren/opt/zmq/include', '/usr/include/uuid', '/usr/include/x86_64\-linux\-gnu']"
.br
.ti -1c
.RI "string \fB_cache\&.LIBDIR\fP = '/home/bviren/opt/zio/lib'"
.br
.ti -1c
.RI "list \fB_cache\&.LIBPATH_CZMQ\fP = ['/home/bviren/opt/zmq/lib']"
.br
.ti -1c
.RI "string \fB_cache\&.LIBPATH_ST\fP = '\-L%s'"
.br
.ti -1c
.RI "list \fB_cache\&.LIBPATH_ZMQ\fP = ['/home/bviren/opt/zmq/lib']"
.br
.ti -1c
.RI "list \fB_cache\&.LIBPATH_ZYRE\fP = ['/home/bviren/opt/zmq/lib']"
.br
.ti -1c
.RI "list \fB_cache\&.LIB_CZMQ\fP = ['czmq']"
.br
.ti -1c
.RI "string \fB_cache\&.LIB_ST\fP = '\-l%s'"
.br
.ti -1c
.RI "list \fB_cache\&.LIB_ZMQ\fP = ['zmq']"
.br
.ti -1c
.RI "list \fB_cache\&.LIB_ZYRE\fP = ['zyre']"
.br
.ti -1c
.RI "list \fB_cache\&.LINKFLAGS_MACBUNDLE\fP = ['\-bundle', '\-undefined', 'dynamic_lookup']"
.br
.ti -1c
.RI "list \fB_cache\&.LINKFLAGS_cxxshlib\fP = ['\-shared']"
.br
.ti -1c
.RI "list \fB_cache\&.LINKFLAGS_cxxstlib\fP = ['\-Wl,\-Bstatic']"
.br
.ti -1c
.RI "list \fB_cache\&.LINK_CXX\fP = ['/usr/bin/g++']"
.br
.ti -1c
.RI "list \fB_cache\&.PKGCONFIG\fP = ['/usr/bin/pkg\-config']"
.br
.ti -1c
.RI "string \fB_cache\&.PREFIX\fP = '/home/bviren/opt/zio'"
.br
.ti -1c
.RI "string \fB_cache\&.RPATH_ST\fP = '\-Wl,\-rpath,%s'"
.br
.ti -1c
.RI "string \fB_cache\&.SHLIB_MARKER\fP = '\-Wl,\-Bdynamic'"
.br
.ti -1c
.RI "string \fB_cache\&.SONAME_ST\fP = '\-Wl,\-h,%s'"
.br
.ti -1c
.RI "string \fB_cache\&.STLIBPATH_ST\fP = '\-L%s'"
.br
.ti -1c
.RI "string \fB_cache\&.STLIB_MARKER\fP = '\-Wl,\-Bstatic'"
.br
.ti -1c
.RI "string \fB_cache\&.STLIB_ST\fP = '\-l%s'"
.br
.ti -1c
.RI "string \fB_cache\&.cxxprogram_PATTERN\fP = '%s'"
.br
.ti -1c
.RI "string \fB_cache\&.cxxshlib_PATTERN\fP = 'lib%s\&.so'"
.br
.ti -1c
.RI "string \fB_cache\&.cxxstlib_PATTERN\fP = 'lib%s\&.a'"
.br
.ti -1c
.RI "list \fB_cache\&.define_key\fP = ['HAVE_ZMQ', 'HAVE_CZMQ', 'HAVE_ZYRE']"
.br
.ti -1c
.RI "string \fB_cache\&.macbundle_PATTERN\fP = '%s\&.bundle'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
