.TH "python Directory Reference" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBtests\fP"
.br
.ti -1c
.RI "directory \fBzio\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsetup\&.py\fP"
.br
.in -1c
