.TH "ack" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ack
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalid\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file test_sml\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ack::valid {}"

.PP
Definition at line 15 of file test_sml\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
