.TH "build" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBversion\fP = 0x2000b00"
.br
.ti -1c
.RI "list \fBtools\fP = [{'tool': 'ar', 'tooldir': None, 'funs': None}, {'tool': 'cxx', 'tooldir': None, 'funs': None}, {'tool': 'g++', 'tooldir': None, 'funs': None}, {'tool': 'compiler_cxx', 'tooldir': None, 'funs': None}, {'tool': 'waf_unit_test', 'tooldir': None, 'funs': None}]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list build\&.tools = [{'tool': 'ar', 'tooldir': None, 'funs': None}, {'tool': 'cxx', 'tooldir': None, 'funs': None}, {'tool': 'g++', 'tooldir': None, 'funs': None}, {'tool': 'compiler_cxx', 'tooldir': None, 'funs': None}, {'tool': 'waf_unit_test', 'tooldir': None, 'funs': None}]"

.PP
Definition at line 2 of file build\&.config\&.py\&.
.SS "int build\&.version = 0x2000b00"

.PP
Definition at line 1 of file build\&.config\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
