.TH "client_protocol" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_protocol
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBactions\fP"
.br
.ti -1c
.RI "struct \fBconnected\fP"
.br
.ti -1c
.RI "struct \fBev_connect\fP"
.br
.ti -1c
.RI "struct \fBev_connected\fP"
.br
.ti -1c
.RI "struct \fBev_disconnect\fP"
.br
.ti -1c
.RI "struct \fBev_disconnected\fP"
.br
.ti -1c
.RI "struct \fBev_error\fP"
.br
.ti -1c
.RI "struct \fBev_fin\fP"
.br
.ti -1c
.RI "struct \fBev_handshake_ack\fP"
.br
.ti -1c
.RI "struct \fBev_payload\fP"
.br
.ti -1c
.RI "struct \fBev_retry\fP"
.br
.ti -1c
.RI "struct \fBevents\fP"
.br
.ti -1c
.RI "struct \fBprotocol\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< std::uint8_t > \fBconst_buffer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBoperator()\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file test_hsm\&.cpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::vector<std::uint8_t> \fBclient_protocol::const_buffer\fP"

.PP
Definition at line 13 of file test_hsm\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "auto client_protocol::operator() ()\fC [inline]\fP"

.PP
Definition at line 115 of file test_hsm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
