.TH "client_protocol::ev_connected" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_protocol::ev_connected
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 24 of file test_hsm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
