.TH "client_protocol::ev_retry" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_protocol::ev_retry
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 30 of file _test_hsm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
