.TH "DirectBinder" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectBinder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBoperator()\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBzio::socket_t\fP & \fBsock\fP"
.br
.ti -1c
.RI "std::string \fBaddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file port\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string DirectBinder::operator() ()\fC [inline]\fP"

.PP
Definition at line 22 of file port\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string DirectBinder::address"

.PP
Definition at line 21 of file port\&.cpp\&.
.SS "\fBzio::socket_t\fP& DirectBinder::sock"

.PP
Definition at line 20 of file port\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
