.TH "inc/zio/exceptions.hpp" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/zio/exceptions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBzio::exception\fP"
.br
.RI "general exception class for zio "
.ti -1c
.RI "class \fBzio::socket_error\fP"
.br
.RI "exception indicating a socket error "
.ti -1c
.RI "class \fBzio::message_error\fP"
.br
.RI "exception indicating message error "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzio\fP"
.br
.RI "implementation of ZIO data flow protocol endpoints "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
