.TH "fin" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fin
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP {}"
.br
.ti -1c
.RI "bool \fBvalid\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file test_sml\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int fin::id {}"

.PP
Definition at line 16 of file test_sml\&.cpp\&.
.SS "bool fin::valid {}"

.PP
Definition at line 16 of file test_sml\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
