.TH "flow_protocol::protocol" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flow_protocol::protocol
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBoperator()\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcredit\fP {0}"
.br
.ti -1c
.RI "int \fBtotal_credit\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file _test_flowsm\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "auto flow_protocol::protocol::operator() ()\fC [inline]\fP"

.PP
Definition at line 68 of file _test_flowsm\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int flow_protocol::protocol::credit {0}"

.PP
Definition at line 65 of file _test_flowsm\&.cpp\&.
.SS "int flow_protocol::protocol::total_credit {0}"

.PP
Definition at line 66 of file _test_flowsm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
