.TH "flow_protocol::ev_bot" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flow_protocol::ev_bot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBflow_protocol::ev_msg\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFlowDirection\fP \fBfdir\fP"
.br
.ti -1c
.RI "\fBcredits_t\fP \fBcredits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file test_flowsm\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcredits_t\fP flow_protocol::ev_bot::credits"

.PP
Definition at line 26 of file test_flowsm\&.cpp\&.
.SS "\fBFlowDirection\fP flow_protocol::ev_bot::fdir"

.PP
Definition at line 25 of file test_flowsm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
