.TH "inc/zio/flow.hpp" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/zio/flow.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/port\&.hpp'\fP
.br
\fC#include 'zio/message\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBzio::flow::Flow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzio\fP"
.br
.RI "implementation of ZIO data flow protocol endpoints "
.ti -1c
.RI " \fBzio::flow\fP"
.br
.RI "ZIO data flow\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBzio::flow::Direction\fP { \fBzio::flow::undefined\fP, \fBzio::flow::extract\fP, \fBzio::flow::inject\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
