.TH "flow_protocol::ev_pay" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flow_protocol::ev_pay
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBflow_protocol::ev_msg\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcredit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file test_flowsm\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int flow_protocol::ev_pay::credit"

.PP
Definition at line 43 of file test_flowsm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
