.TH "flow_protocol::ev_recving" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flow_protocol::ev_recving
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcredit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file _test_flowsm\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int flow_protocol::ev_recving::credit"

.PP
Definition at line 37 of file _test_flowsm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
