.TH "HostPortBinder" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HostPortBinder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBoperator()\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBzio::socket_t\fP & \fBsock\fP"
.br
.ti -1c
.RI "std::string \fBhostname\fP"
.br
.ti -1c
.RI "int \fBtcpportnum\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file port\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string HostPortBinder::operator() ()\fC [inline]\fP"

.PP
Definition at line 34 of file port\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string HostPortBinder::hostname"

.PP
Definition at line 32 of file port\&.cpp\&.
.SS "\fBzio::socket_t\fP& HostPortBinder::sock"

.PP
Definition at line 31 of file port\&.cpp\&.
.SS "int HostPortBinder::tcpportnum {0}"

.PP
Definition at line 33 of file port\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
