.TH "md_python_rule__t_o_d_o" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_python_rule__t_o_d_onew operators 
 \- 
.IP "1." 4
onlycontains/allin
.PP
.IP "1." 4
all (modify \fCand\fP to accept multi values)
.PP
.IP "1." 4
any (modify \fCor\fP to accept multi values)
.PP
.IP "1." 4
list
.PP
.IP "1." 4
uniq/set
.PP
.IP "1." 4
bool/notempty
.PP
.IP "1." 4
empty
.PP
.IP "1." 4
unpack 
.PP

