.TH "md_python_rule__r_e_a_d_m_e" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_python_rule__r_e_a_d_m_eRule 
 \- A rule engine written in python\&.
.PP
The rule is a json/yaml string or python object of a list expression\&. The expression is like \fC[op, arg0, arg1, \&.\&.\&., argn]\fP, the \fCop\fP is the operator, and \fCarg0\&.\&.n\fP is the arguments for the operator\&. Any argument can be another expression\&.
.PP
For writing convenience, the first argument will be tried to resolve as the context parameter\&. Or, you can just use the special \fCvar\fP operator to indicate the context parameter\&.
.PP
.SS "Installing"
.PP
.PP
.nf
pip install rule
.fi
.PP
.PP
.SS "Usage"
.PP
.PP
.nf
>>> from rule import Rule
>>>
>>> context = dict(a=1, world='hello')
>>> Rule(['=', ['var', 'a'], 1])\&.match(context)
True
>>> Rule("['=', ['var', 'a'], 1]")\&.match(context)
True
>>> Rule(['=', 'a', 1])\&.match(context)
True
>>> Rule(['=', 'hello', 'hello'])\&.match(context)
True
>>> Rule(['=', 'world', 'hello'])\&.match(context)
True
>>> Rule(['<', 'a', 10])\&.match(context)
True
>>> Rule(['=', ['>', 'a', 10], False])\&.match(context)
True
>>>
>>> context = dict(ldap_id='Harry', hosts='sa,sb,sc', reason='hehe', nologin=False,
\&.\&.\&.                group='wheel,sysadmin,platform', package='dev-python/sa-tools',
\&.\&.\&.                branch='release', cc='Tony,Mike',)
>>> Rule(['contains', 'hosts', 'sa,'])\&.match(context)
True
>>> Rule(['contains', ['split', 'hosts', ','], 'sa'])\&.match(context)
True
>>> Rule(['in', 'branch', 'master', 'release'])\&.match(context)
True
>>> Rule(['=', 'ldap_id', 'Harry'])\&.match(context)
True
>>> Rule(['match', 'package', 'dev-python/*'])\&.match(context)
True
>>> Rule(['regex', 'package', 'dev-python/\&.*'])\&.match(context)
True
>>> Rule(['is', 'nologin', False])\&.match(context)
True
.fi
.PP
.PP
See \fCrule/op\&.py\fP for more supported operators\&.
.PP
.SS "Development"
.PP
.PP
.nf
make init
# make install
make test
.fi
.PP
.PP
.SS "License"
.PP
http://tclh123.mit-license.org/ 
