.TH "nlohmann::detail::exception" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::exception \- general exception of the \fBbasic_json\fP class  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits exception\&.
.PP
Inherited by \fBnlohmann::detail::invalid_iterator\fP, \fBnlohmann::detail::other_error\fP, \fBnlohmann::detail::out_of_range\fP, \fBnlohmann::detail::parse_error\fP, and \fBnlohmann::detail::type_error\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJSON_HEDLEY_RETURNS_NON_NULL\fP const char * \fBwhat\fP () const noexcept override"
.br
.RI "returns the explanatory string "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBid\fP"
.br
.RI "the id of the exception "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBexception\fP (int id_, const char *what_arg)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBstd::string\fP \fBname\fP (const \fBstd::string\fP &ename, int id_)"
.br
.in -1c
.SH "Detailed Description"
.PP 
general exception of the \fBbasic_json\fP class 

This class is an extension of \fCstd::exception\fP objects with a member \fIid\fP for exception ids\&. It is used as the base class for all exceptions thrown by the \fBbasic_json\fP class\&. This class can hence be used as 'wildcard' to catch exceptions\&.
.PP
Subclasses:
.IP "\(bu" 2
\fBparse_error\fP for exceptions indicating a parse error
.IP "\(bu" 2
\fBinvalid_iterator\fP for exceptions indicating errors with iterators
.IP "\(bu" 2
\fBtype_error\fP for exceptions indicating executing a member function with a wrong type
.IP "\(bu" 2
\fBout_of_range\fP for exceptions indicating access out of the defined range
.IP "\(bu" 2
\fBother_error\fP for exceptions indicating other library errors
.PP
.PP
{The following code shows how arbitrary library exceptions can be caught\&.,exception}
.PP
\fBSince:\fP
.RS 4
version 3\&.0\&.0 
.RE
.PP

.PP
Definition at line 1864 of file json\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "nlohmann::detail::exception::exception (int id_, const char * what_arg)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 1879 of file json\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBstd::string\fP nlohmann::detail::exception::name (const \fBstd::string\fP & ename, int id_)\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1881 of file json\&.hpp\&.
.SS "\fBJSON_HEDLEY_RETURNS_NON_NULL\fP const char* nlohmann::detail::exception::what () const\fC [inline]\fP, \fC [override]\fP, \fC [noexcept]\fP"

.PP
returns the explanatory string 
.PP
Definition at line 1869 of file json\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const int nlohmann::detail::exception::id"

.PP
the id of the exception 
.PP
Definition at line 1875 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
