.TH "nlohmann::adl_serializer< typename, typename >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::adl_serializer< typename, typename > \- default JSONSerializer template argument  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType , typename ValueType > static auto \fBfrom_json\fP (BasicJsonType &&j, ValueType &val) noexcept(noexcept(::nlohmann::from_json(std::forward< BasicJsonType >(j), val))) \-> decltype(::nlohmann::from_json(std::forward< BasicJsonType >(j), val), void())"
.br
.RI "convert a JSON value to any value type "
.ti -1c
.RI "template<typename BasicJsonType , typename ValueType > static auto \fBto_json\fP (BasicJsonType &j, ValueType &&val) noexcept(noexcept(::nlohmann::to_json(j, std::forward< ValueType >(val)))) \-> decltype(::nlohmann::to_json(j, std::forward< ValueType >(val)), void())"
.br
.RI "convert any value type to a JSON value "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename, typename>
.br
struct nlohmann::adl_serializer< typename, typename >"
default JSONSerializer template argument 

This serializer ignores the template arguments and uses ADL (\fCargument-dependent lookup\fP) for serialization\&. 
.PP
Definition at line 2409 of file json\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename , typename > template<typename BasicJsonType , typename ValueType > static auto \fBnlohmann::adl_serializer\fP< typename, typename >::from_json (BasicJsonType && j, ValueType & val) \-> decltype(::nlohmann::from_json(std::forward<BasicJsonType>(j), val), void())
    \fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
convert a JSON value to any value type This function is usually called by the \fC\fBget()\fP\fP function of the \fBbasic_json\fP class (either explicit or via conversion operators)\&.
.PP
\fBParameters:\fP
.RS 4
\fIj\fP JSON value to read from 
.br
\fIval\fP value to write to 
.RE
.PP

.PP
Definition at line 3810 of file json\&.hpp\&.
.SS "template<typename , typename > template<typename BasicJsonType , typename ValueType > static auto \fBnlohmann::adl_serializer\fP< typename, typename >::to_json (BasicJsonType & j, ValueType && val) \-> decltype(::nlohmann::to_json(j, std::forward<ValueType>(val)), void())
    \fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
convert any value type to a JSON value This function is usually called by the constructors of the \fBbasic_json\fP class\&.
.PP
\fBParameters:\fP
.RS 4
\fIj\fP JSON value to write to 
.br
\fIval\fP value to read from 
.RE
.PP

.PP
Definition at line 3827 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
