.TH "nlohmann::detail::detector< Default, void_t< Op< Args... > >, Op, Args... >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::detector< Default, void_t< Op< Args... > >, Op, Args... >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_t\fP = std::true_type"
.br
.ti -1c
.RI "using \fBtype\fP = Op< Args\&.\&.\&. >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Default, template< class\&.\&.\&. > class Op, class\&.\&.\&. Args>
.br
struct nlohmann::detail::detector< Default, void_t< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >"

.PP
Definition at line 2357 of file json\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::\fBtype\fP =  Op<Args\&.\&.\&.>"

.PP
Definition at line 2360 of file json\&.hpp\&.
.SS "template<class Default , template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBnlohmann::detail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::\fBvalue_t\fP =  std::true_type"

.PP
Definition at line 2359 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
