.TH "nlohmann::detail::external_constructor< value_t::string >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::external_constructor< value_t::string >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType > static \fBvoid\fP \fBconstruct\fP (BasicJsonType &j, const typename BasicJsonType::string_t &s)"
.br
.ti -1c
.RI "template<typename BasicJsonType > static \fBvoid\fP \fBconstruct\fP (BasicJsonType &j, typename BasicJsonType::string_t &&s)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleStringType , enable_if_t< not std::is_same< CompatibleStringType, typename BasicJsonType::string_t >::value, int >  = 0> static \fBvoid\fP \fBconstruct\fP (BasicJsonType &j, const CompatibleStringType &str)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct nlohmann::detail::external_constructor< value_t::string >"

.PP
Definition at line 3485 of file json\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType > static \fBvoid\fP \fBnlohmann::detail::external_constructor\fP< \fBvalue_t::string\fP >::construct (BasicJsonType & j, const typename BasicJsonType::string_t & s)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 3488 of file json\&.hpp\&.
.SS "template<typename BasicJsonType > static \fBvoid\fP \fBnlohmann::detail::external_constructor\fP< \fBvalue_t::string\fP >::construct (BasicJsonType & j, typename BasicJsonType::string_t && s)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 3496 of file json\&.hpp\&.
.SS "template<typename BasicJsonType , typename CompatibleStringType , enable_if_t< not std::is_same< CompatibleStringType, typename BasicJsonType::string_t >::value, int >  = 0> static \fBvoid\fP \fBnlohmann::detail::external_constructor\fP< \fBvalue_t::string\fP >::construct (BasicJsonType & j, const CompatibleStringType & str)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 3506 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
