.TH "nlohmann::detail::is_basic_json< typename >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_basic_json< typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename>
.br
struct nlohmann::detail::is_basic_json< typename >"

.PP
Definition at line 2476 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
