.TH "nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits true_type\&.
.SH "Detailed Description"
.PP 
Definition at line 2479 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
