.TH "nlohmann::detail::conjunction< B1, Bn... >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::conjunction< B1, Bn... >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits type< bool(B1::value), conjunction< Bn\&.\&.\&. >, B1 >\&.
.SH "Detailed Description"
.PP 

.SS "template<class B1, class\&.\&.\&. Bn>
.br
struct nlohmann::detail::conjunction< B1, Bn\&.\&.\&. >"

.PP
Definition at line 2802 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
