.TH "nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits \fBnlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename BasicJsonType, typename CompatibleArrayType>
.br
struct nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >"

.PP
Definition at line 2709 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
