.TH "nlohmann::detail::binary_reader< BasicJsonType, SAX >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::binary_reader< BasicJsonType, SAX > \- deserialization of CBOR, MessagePack, and UBJSON values  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbinary_reader\fP (\fBinput_adapter_t\fP adapter)"
.br
.RI "create a binary reader "
.ti -1c
.RI "\fBbinary_reader\fP (const \fBbinary_reader\fP &)=delete"
.br
.ti -1c
.RI "\fBbinary_reader\fP (\fBbinary_reader\fP &&)=default"
.br
.ti -1c
.RI "\fBbinary_reader\fP & \fBoperator=\fP (const \fBbinary_reader\fP &)=delete"
.br
.ti -1c
.RI "\fBbinary_reader\fP & \fBoperator=\fP (\fBbinary_reader\fP &&)=default"
.br
.ti -1c
.RI "\fB~binary_reader\fP ()=default"
.br
.ti -1c
.RI "bool \fBsax_parse\fP (const \fBinput_format_t\fP format, json_sax_t *sax_, const bool \fBstrict\fP=true)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr bool \fBlittle_endianess\fP (int num=1) noexcept"
.br
.RI "determine system byte order "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BasicJsonType, typename SAX = json_sax_dom_parser<BasicJsonType>>
.br
class nlohmann::detail::binary_reader< BasicJsonType, SAX >"
deserialization of CBOR, MessagePack, and UBJSON values 
.PP
Definition at line 5175 of file json\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename BasicJsonType , typename SAX  = json_sax_dom_parser<BasicJsonType>> \fBnlohmann::detail::binary_reader\fP< BasicJsonType, SAX >::\fBbinary_reader\fP (\fBinput_adapter_t\fP adapter)\fC [inline]\fP, \fC [explicit]\fP"

.PP
create a binary reader 
.PP
\fBParameters:\fP
.RS 4
\fIadapter\fP input adapter to read from 
.RE
.PP

.PP
Definition at line 5189 of file json\&.hpp\&.
.SS "template<typename BasicJsonType , typename SAX  = json_sax_dom_parser<BasicJsonType>> \fBnlohmann::detail::binary_reader\fP< BasicJsonType, SAX >::\fBbinary_reader\fP (const \fBbinary_reader\fP< BasicJsonType, SAX > &)\fC [delete]\fP"

.SS "template<typename BasicJsonType , typename SAX  = json_sax_dom_parser<BasicJsonType>> \fBnlohmann::detail::binary_reader\fP< BasicJsonType, SAX >::\fBbinary_reader\fP (\fBbinary_reader\fP< BasicJsonType, SAX > &&)\fC [default]\fP"

.SS "template<typename BasicJsonType , typename SAX  = json_sax_dom_parser<BasicJsonType>> \fBnlohmann::detail::binary_reader\fP< BasicJsonType, SAX >::~\fBbinary_reader\fP ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType , typename SAX  = json_sax_dom_parser<BasicJsonType>> static constexpr bool \fBnlohmann::detail::binary_reader\fP< BasicJsonType, SAX >::little_endianess (int num = \fC1\fP)\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
determine system byte order 
.PP
\fBReturns:\fP
.RS 4
true if and only if system's byte order is little endian
.RE
.PP
\fBNote:\fP
.RS 4
from http://stackoverflow.com/a/1001328/266378 
.RE
.PP

.PP
Definition at line 5268 of file json\&.hpp\&.
.SS "template<typename BasicJsonType , typename SAX  = json_sax_dom_parser<BasicJsonType>> \fBbinary_reader\fP& \fBnlohmann::detail::binary_reader\fP< BasicJsonType, SAX >::operator= (const \fBbinary_reader\fP< BasicJsonType, SAX > &)\fC [delete]\fP"

.SS "template<typename BasicJsonType , typename SAX  = json_sax_dom_parser<BasicJsonType>> \fBbinary_reader\fP& \fBnlohmann::detail::binary_reader\fP< BasicJsonType, SAX >::operator= (\fBbinary_reader\fP< BasicJsonType, SAX > &&)\fC [default]\fP"

.SS "template<typename BasicJsonType , typename SAX  = json_sax_dom_parser<BasicJsonType>> bool \fBnlohmann::detail::binary_reader\fP< BasicJsonType, SAX >::sax_parse (const \fBinput_format_t\fP format, json_sax_t * sax_, const bool strict = \fCtrue\fP)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIformat\fP the binary format to parse 
.br
\fIsax_\fP a SAX event processor 
.br
\fIstrict\fP whether to expect the input to be consumed completed
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 5210 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
