.TH "nlohmann::detail::external_constructor< value_t::number_integer >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::external_constructor< value_t::number_integer >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType > static \fBvoid\fP \fBconstruct\fP (BasicJsonType &j, typename BasicJsonType::number_integer_t val) noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct nlohmann::detail::external_constructor< value_t::number_integer >"

.PP
Definition at line 3539 of file json\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType > static \fBvoid\fP \fBnlohmann::detail::external_constructor\fP< \fBvalue_t::number_integer\fP >::construct (BasicJsonType & j, typename BasicJsonType::number_integer_t val)\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
Definition at line 3542 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
