.TH "nlohmann::detail::input_buffer_adapter" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::input_buffer_adapter \- input adapter for buffer input  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits \fBnlohmann::detail::input_adapter_protocol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinput_buffer_adapter\fP (const char *b, const std::size_t l) noexcept"
.br
.ti -1c
.RI "\fBinput_buffer_adapter\fP (const \fBinput_buffer_adapter\fP &)=delete"
.br
.ti -1c
.RI "\fBinput_buffer_adapter\fP & \fBoperator=\fP (\fBinput_buffer_adapter\fP &)=delete"
.br
.ti -1c
.RI "\fBinput_buffer_adapter\fP (\fBinput_buffer_adapter\fP &&)=delete"
.br
.ti -1c
.RI "\fBinput_buffer_adapter\fP & \fBoperator=\fP (\fBinput_buffer_adapter\fP &&)=delete"
.br
.ti -1c
.RI "\fB~input_buffer_adapter\fP () override=default"
.br
.ti -1c
.RI "std::char_traits< char >::int_type \fBget_character\fP () noexcept override"
.br
.RI "get a character [0,255] or std::char_traits<char>::eof()\&. "
.in -1c
.SH "Detailed Description"
.PP 
input adapter for buffer input 
.PP
Definition at line 3994 of file json\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "nlohmann::detail::input_buffer_adapter::input_buffer_adapter (const char * b, const std::size_t l)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 3997 of file json\&.hpp\&.
.SS "nlohmann::detail::input_buffer_adapter::input_buffer_adapter (const \fBinput_buffer_adapter\fP &)\fC [delete]\fP"

.SS "nlohmann::detail::input_buffer_adapter::input_buffer_adapter (\fBinput_buffer_adapter\fP &&)\fC [delete]\fP"

.SS "nlohmann::detail::input_buffer_adapter::~input_buffer_adapter ()\fC [override]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::char_traits<char>::int_type nlohmann::detail::input_buffer_adapter::get_character ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"

.PP
get a character [0,255] or std::char_traits<char>::eof()\&. 
.PP
Implements \fBnlohmann::detail::input_adapter_protocol\fP\&.
.PP
Definition at line 4008 of file json\&.hpp\&.
.SS "\fBinput_buffer_adapter\fP& nlohmann::detail::input_buffer_adapter::operator= (\fBinput_buffer_adapter\fP &)\fC [delete]\fP"

.SS "\fBinput_buffer_adapter\fP& nlohmann::detail::input_buffer_adapter::operator= (\fBinput_buffer_adapter\fP &&)\fC [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
