.TH "nlohmann::detail::has_to_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::has_to_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBserializer\fP = typename BasicJsonType::template json_serializer< T, \fBvoid\fP >"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr bool \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BasicJsonType, typename T>
.br
struct nlohmann::detail::has_to_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >"

.PP
Definition at line 2554 of file json\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename BasicJsonType , typename T > using \fBnlohmann::detail::has_to_json\fP< BasicJsonType, T, \fBenable_if_t\fP< not \fBis_basic_json\fP< T >::\fBvalue\fP > >::\fBserializer\fP =  typename BasicJsonType::template json_serializer<T, \fBvoid\fP>"

.PP
Definition at line 2556 of file json\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename BasicJsonType , typename T > constexpr bool \fBnlohmann::detail::has_to_json\fP< BasicJsonType, T, \fBenable_if_t\fP< not \fBis_basic_json\fP< T >::value > >::value\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
        is_detected_exact<void, to_json_function, serializer, BasicJsonType&,
        T>::value
.fi
.PP
Definition at line 2558 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
