.TH "nlohmann::detail::index_sequence< Ints >" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::index_sequence< Ints >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = \fBindex_sequence\fP"
.br
.ti -1c
.RI "using \fBvalue_type\fP = std::size_t"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr std::size_t \fBsize\fP () noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<std::size_t\&.\&.\&. Ints>
.br
struct nlohmann::detail::index_sequence< Ints >"

.PP
Definition at line 2199 of file json\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<std::size_t\&.\&.\&. Ints> using \fBnlohmann::detail::index_sequence\fP< Ints >::\fBtype\fP =  \fBindex_sequence\fP"

.PP
Definition at line 2201 of file json\&.hpp\&.
.SS "template<std::size_t\&.\&.\&. Ints> using \fBnlohmann::detail::index_sequence\fP< Ints >::\fBvalue_type\fP =  std::size_t"

.PP
Definition at line 2202 of file json\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<std::size_t\&.\&.\&. Ints> static constexpr std::size_t \fBnlohmann::detail::index_sequence\fP< Ints >::size ()\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
Definition at line 2203 of file json\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
