.TH "python/rule/rule/op.py" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/rule/rule/op.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrule\&.op\&.Op\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Var\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Eq\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.In\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Startswith\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Endswith\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Num\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.String\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Lower\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Upper\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Split\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Match\fP"
.br
.ti -1c
.RI "class \fBrule\&.op\&.Regex\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrule\&.op\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrule\&.op\&.register\fP (aliases=None)"
.br
.ti -1c
.RI "def \fBrule\&.op\&.quick_op\fP (name, aliases=None)"
.br
.ti -1c
.RI "def \fBrule\&.op\&.get_op\fP (name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBrule\&.op\&.simple_ops\fP"
.br
.ti -1c
.RI "\fBrule\&.op\&.name\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
