.TH "inc/zio/port.hpp" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/zio/port.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/peer\&.hpp'\fP
.br
\fC#include 'zio/message\&.hpp'\fP
.br
\fC#include 'zio/interned\&.hpp'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBzio::Port\fP"
.br
.RI "a port holds a socket in the context of a node "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzio\fP"
.br
.RI "implementation of ZIO data flow protocol endpoints "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< Port > \fBzio::portptr_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
