.TH "src/port.cpp" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/port.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/port\&.hpp'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDirectBinder\fP"
.br
.ti -1c
.RI "struct \fBHostPortBinder\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
