.TH "python/zio/port.py" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/zio/port.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBzio\&.port\&.Port\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzio\&.port\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzio\&.port\&.bind_address\fP (sock, \fBaddr\fP)"
.br
.ti -1c
.RI "def \fBzio\&.port\&.bind_hostport\fP (sock, host, port)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBzio\&.port\&.ephemeral_port_range\fP = (49152, 65535)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
