.TH "rule.op.Split" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule.op.Split
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrule\&.op\&.Op\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBcalc\fP (self, \fBcontext\fP, args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
split(sep=None, maxsplit=-1)
.fi
.PP
 
.PP
Definition at line 155 of file op\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def rule\&.op\&.Split\&.calc ( self,  context,  args)"

.PP
Definition at line 157 of file op\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
