.TH "rule.op.Op" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule.op.Op
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBrule\&.op\&.Endswith\fP, \fBrule\&.op\&.Eq\fP, \fBrule\&.op\&.In\fP, \fBrule\&.op\&.Lower\fP, \fBrule\&.op\&.Match\fP, \fBrule\&.op\&.Num\fP, \fBrule\&.op\&.Regex\fP, \fBrule\&.op\&.Split\fP, \fBrule\&.op\&.Startswith\fP, \fBrule\&.op\&.String\fP, \fBrule\&.op\&.Upper\fP, and \fBrule\&.op\&.Var\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__call__\fP (self, \fBcontext\fP, args)"
.br
.ti -1c
.RI "def \fBcalc\fP (self, \fBcontext\fP, args)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file op\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def rule\&.op\&.Op\&.__call__ ( self,  context,  args)"

.PP
Definition at line 31 of file op\&.py\&.
.SS "def rule\&.op\&.Op\&.calc ( self,  context,  args)"

.PP
Definition at line 35 of file op\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "string rule\&.op\&.Op\&.name = ''\fC [static]\fP"

.PP
Definition at line 29 of file op\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
