.TH "rule.op" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule.op
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEndswith\fP"
.br
.ti -1c
.RI "class \fBEq\fP"
.br
.ti -1c
.RI "class \fBIn\fP"
.br
.ti -1c
.RI "class \fBLower\fP"
.br
.ti -1c
.RI "class \fBMatch\fP"
.br
.ti -1c
.RI "class \fBNum\fP"
.br
.ti -1c
.RI "class \fBOp\fP"
.br
.ti -1c
.RI "class \fBRegex\fP"
.br
.ti -1c
.RI "class \fBSplit\fP"
.br
.ti -1c
.RI "class \fBStartswith\fP"
.br
.ti -1c
.RI "class \fBString\fP"
.br
.ti -1c
.RI "class \fBUpper\fP"
.br
.ti -1c
.RI "class \fBVar\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBregister\fP (aliases=None)"
.br
.ti -1c
.RI "def \fBquick_op\fP (\fBname\fP, aliases=None)"
.br
.ti -1c
.RI "def \fBget_op\fP (\fBname\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBsimple_ops\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def rule\&.op\&.get_op ( name)"

.PP
Definition at line 173 of file op\&.py\&.
.SS "def rule\&.op\&.quick_op ( name,  aliases = \fCNone\fP)"

.PP
Definition at line 60 of file op\&.py\&.
.SS "def rule\&.op\&.register ( aliases = \fCNone\fP)"

.PP
Definition at line 13 of file op\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "rule\&.op\&.name"

.PP
Definition at line 20 of file op\&.py\&.
.SS "list rule\&.op\&.simple_ops"

.PP
Definition at line 68 of file op\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
