.TH "rule.Expr" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule.Expr
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, rule)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fBbuild_expr\fP (self, rule)"
.br
.ti -1c
.RI "def \fBmatch\fP (self, \fBcontext\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBop\fP"
.br
.ti -1c
.RI "\fBargs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file __init__\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def rule\&.Expr\&.__init__ ( self,  rule)"

.PP
Definition at line 16 of file __init__\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def rule\&.Expr\&.__str__ ( self)"

.PP
Definition at line 25 of file __init__\&.py\&.
.SS "def rule\&.Expr\&.build_expr ( self,  rule)"

.PP
Definition at line 30 of file __init__\&.py\&.
.SS "def rule\&.Expr\&.match ( self,  context)"

.PP
Definition at line 35 of file __init__\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "rule\&.Expr\&.args"

.PP
Definition at line 21 of file __init__\&.py\&.
.SS "rule\&.Expr\&.op"

.PP
Definition at line 20 of file __init__\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
