.TH "rule" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rule
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBop\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExpr\fP"
.br
.ti -1c
.RI "class \fBRule\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBis_simple_type\fP (obj)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcontext\fP = dict(a=1, world='hello')"
.br
.ti -1c
.RI "list \fBrules\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def rule\&.is_simple_type ( obj)"

.PP
Definition at line 11 of file __init__\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "rule\&.context = dict(a=1, world='hello')"

.PP
Definition at line 99 of file __init__\&.py\&.
.SS "list rule\&.rules"
\fBInitial value:\fP
.PP
.nf
1 =  [
2         Rule("['=', ['var', 'a'], 1]"),
3         Rule(['=', ['var', 'a'], 1]),
4         Rule(['=', 'a', 1]),
5         Rule(['=', 'hello', 'hello']),
6         Rule(['=', 'world', 'hello']),
7         Rule(['<', 'a', 10]),
8         Rule(['=', ['>', 'a', 10], False]),
9         ]
.fi
.PP
Definition at line 100 of file __init__\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
