.TH "sender" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sender
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class TMsg > constexpr void \fBsend\fP (const TMsg &msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file test_sml\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class TMsg > constexpr void sender::send (const TMsg & msg)\fC [inline]\fP"

.PP
Definition at line 10 of file test_sml\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
