.TH "python/setup.py" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/setup.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsetup\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsetup\&.python_requires\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
