.TH "setup" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBversion\fP = '0\&.1\&.2bv'"
.br
.ti -1c
.RI "list \fBrequirements\fP"
.br
.ti -1c
.RI "string \fBentry_points\fP"
.br
.ti -1c
.RI "list \fBscripts\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBlong_description\fP"
.br
.ti -1c
.RI "\fBlong_description_content_type\fP"
.br
.ti -1c
.RI "\fBclassifiers\fP"
.br
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBkeywords\fP"
.br
.ti -1c
.RI "\fBauthor\fP"
.br
.ti -1c
.RI "\fBauthor_email\fP"
.br
.ti -1c
.RI "\fBlicense\fP"
.br
.ti -1c
.RI "\fBpackages\fP"
.br
.ti -1c
.RI "\fBinclude_package_data\fP"
.br
.ti -1c
.RI "\fBzip_safe\fP"
.br
.ti -1c
.RI "\fBinstall_requires\fP"
.br
.ti -1c
.RI "\fBpython_requires\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "setup\&.author"

.PP
Definition at line 41 of file setup\&.py\&.
.SS "setup\&.author_email"

.PP
Definition at line 42 of file setup\&.py\&.
.SS "setup\&.classifiers"

.PP
Definition at line 30 of file setup\&.py\&.
.SS "setup\&.description"

.PP
Definition at line 25 of file setup\&.py\&.
.SS "setup\&.entry_points"
\fBInitial value:\fP
.PP
.nf
1 =  """
2       [console_scripts]
3       # rule = rule\&.cli:main
4       """
.fi
.PP
Definition at line 15 of file setup\&.py\&.
.SS "setup\&.include_package_data"

.PP
Definition at line 45 of file setup\&.py\&.
.SS "setup\&.install_requires"

.PP
Definition at line 50 of file setup\&.py\&.
.SS "setup\&.keywords"

.PP
Definition at line 40 of file setup\&.py\&.
.SS "setup\&.license"

.PP
Definition at line 43 of file setup\&.py\&.
.SS "setup\&.long_description"

.PP
Definition at line 26 of file setup\&.py\&.
.SS "setup\&.long_description_content_type"

.PP
Definition at line 27 of file setup\&.py\&.
.SS "setup\&.name"

.PP
Definition at line 23 of file setup\&.py\&.
.SS "setup\&.packages"

.PP
Definition at line 44 of file setup\&.py\&.
.SS "setup\&.python_requires"

.PP
Definition at line 11 of file setup\&.py\&.
.SS "list setup\&.requirements"
\fBInitial value:\fP
.PP
.nf
1 =  [
2     'setuptools',
3     'six',
4     'pyyaml',
5 ]
.fi
.PP
Definition at line 8 of file setup\&.py\&.
.SS "setup\&.scripts"
\fBInitial value:\fP
.PP
.nf
1 =  [
2 ]
.fi
.PP
Definition at line 20 of file setup\&.py\&.
.SS "setup\&.url"

.PP
Definition at line 39 of file setup\&.py\&.
.SS "setup\&.version = '0\&.1\&.2bv'"

.PP
Definition at line 5 of file setup\&.py\&.
.SS "setup\&.zip_safe"

.PP
Definition at line 46 of file setup\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
