.TH "setup" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBauthor\fP"
.br
.ti -1c
.RI "\fBauthor_email\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBpackages\fP"
.br
.ti -1c
.RI "\fBpython_requires\fP"
.br
.ti -1c
.RI "\fBinstall_requires\fP"
.br
.ti -1c
.RI "\fBentry_points\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "setup\&.author"

.PP
Definition at line 6 of file setup\&.py\&.
.SS "setup\&.author_email"

.PP
Definition at line 7 of file setup\&.py\&.
.SS "setup\&.description"

.PP
Definition at line 8 of file setup\&.py\&.
.SS "setup\&.entry_points"

.PP
Definition at line 21 of file setup\&.py\&.
.SS "setup\&.install_requires"

.PP
Definition at line 12 of file setup\&.py\&.
.SS "setup\&.name"

.PP
Definition at line 4 of file setup\&.py\&.
.SS "setup\&.packages"

.PP
Definition at line 10 of file setup\&.py\&.
.SS "setup\&.python_requires"

.PP
Definition at line 11 of file setup\&.py\&.
.SS "setup\&.url"

.PP
Definition at line 9 of file setup\&.py\&.
.SS "setup\&.version"

.PP
Definition at line 5 of file setup\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
