.TH "tcp_release" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_release
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBoperator()\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file test_sml\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "auto tcp_release::operator() () const\fC [inline]\fP"
Initial state: *initial_state Transition DSL: src_state + event [ guard ] / action = dst_state
.PP
Definition at line 32 of file test_sml\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
