.TH "test_node.TestNode" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_node.TestNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_noport\fP (self)"
.br
.ti -1c
.RI "def \fBtest_pingpong\fP (self)"
.br
.ti -1c
.RI "def \fBtearDown\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnode\fP"
.br
.ti -1c
.RI "\fBcnode\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBorigin\fP = 42"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file test_node\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_node\&.TestNode\&.setUp ( self)"

.PP
Definition at line 16 of file test_node\&.py\&.
.SS "def test_node\&.TestNode\&.tearDown ( self)"

.PP
Definition at line 51 of file test_node\&.py\&.
.SS "def test_node\&.TestNode\&.test_noport ( self)"

.PP
Definition at line 27 of file test_node\&.py\&.
.SS "def test_node\&.TestNode\&.test_pingpong ( self)"

.PP
Definition at line 34 of file test_node\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "test_node\&.TestNode\&.cnode"

.PP
Definition at line 22 of file test_node\&.py\&.
.SS "int test_node\&.TestNode\&.origin = 42\fC [static]\fP"

.PP
Definition at line 14 of file test_node\&.py\&.
.SS "test_node\&.TestNode\&.snode"

.PP
Definition at line 17 of file test_node\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
