.TH "test/test_exceptions.cxx" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_exceptions.cxx
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/exceptions\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 5 of file test_exceptions\&.cxx\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
