.TH "test/test_encoding.cpp" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_encoding.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/cppzmq\&.hpp'\fP
.br
\fC#include 'zio/main\&.hpp'\fP
.br
\fC#include 'zio/logging\&.hpp'\fP
.br
\fC#include <czmq\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"
Test compatibility of cppzmq and CZMQ single/multipart codec\&. 
.PP
Definition at line 11 of file test_encoding\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
