.TH "test/test_cs.cpp" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_cs.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <czmq\&.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_owoa\fP (bool backwards, const char *\fBaddr\fP)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 115 of file test_cs\&.cpp\&.
.SS "void test_owoa (bool backwards, const char * addr)"

.PP
Definition at line 6 of file test_cs\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
