.TH "python/tests/test_wedontknow.py" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/tests/test_wedontknow.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest_wedontknow\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtest_wedontknow\&.p1\fP = pyre\&.Pyre('p1')"
.br
.ti -1c
.RI "\fBtest_wedontknow\&.p2\fP = pyre\&.Pyre('p2')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
