.TH "test_peer" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_peer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestPeer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger('zio\&.peer')"
.br
.ti -1c
.RI "\fBlevel\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "test_peer\&.level"

.PP
Definition at line 5 of file test_peer\&.py\&.
.SS "test_peer\&.logger = logging\&.getLogger('zio\&.peer')"

.PP
Definition at line 4 of file test_peer\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
