.TH "test/test_flow.cpp" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_flow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/flow\&.hpp'\fP
.br
\fC#include 'zio/node\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"
const char* addr = 'inproc://testflow';
.PP
const char* addr = 'tcp://127\&.0\&.0\&.1:5678'; 
.PP
Definition at line 8 of file test_flow\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
