.TH "test_wedontknow" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_wedontknow
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBp1\fP = pyre\&.Pyre('p1')"
.br
.ti -1c
.RI "\fBp2\fP = pyre\&.Pyre('p2')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "test_wedontknow\&.p1 = pyre\&.Pyre('p1')"

.PP
Definition at line 5 of file test_wedontknow\&.py\&.
.SS "test_wedontknow\&.p2 = pyre\&.Pyre('p2')"

.PP
Definition at line 7 of file test_wedontknow\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
