.TH "test/test_tcs.cpp" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_tcs.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/cppzmq\&.hpp'\fP
.br
\fC#include 'zio/logging\&.hpp'\fP
.br
\fC#include 'zio/main\&.hpp'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <map>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::chrono::duration< int64_t, std::micro > \fBmicroseconds_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBserver_type\fP = ZMQ_SERVER"
.br
.ti -1c
.RI "const int \fBclient_type\fP = ZMQ_CLIENT"
.br
.ti -1c
.RI "const char * \fBaddr\fP = 'ipc://test_tcs\&.ipc'"
.br
.RI "inproc hangs\&. no messages ever get received by server\&. tcp/ipc okay\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::chrono::duration<int64_t,std::micro> \fBmicroseconds_type\fP"

.PP
Definition at line 18 of file test_tcs\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 156 of file test_tcs\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const char* addr = 'ipc://test_tcs\&.ipc'"

.PP
inproc hangs\&. no messages ever get received by server\&. tcp/ipc okay\&. 
.PP
Definition at line 16 of file test_tcs\&.cpp\&.
.SS "const int client_type = ZMQ_CLIENT"

.PP
Definition at line 11 of file test_tcs\&.cpp\&.
.SS "const int server_type = ZMQ_SERVER"

.PP
Definition at line 10 of file test_tcs\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
