.TH "test_broker" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_broker
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBclient_actor\fP (ctx, pipe, args)"
.br
.ti -1c
.RI "def \fBtest_broker\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBserver_address\fP = 'tcp://127\&.0\&.0\&.1:5679'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Test flow broker with example handler

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def test_broker\&.client_actor ( ctx,  pipe,  args)"

.PP
Definition at line 15 of file test_broker\&.py\&.
.SS "def test_broker\&.test_broker ()"

.PP
Definition at line 42 of file test_broker\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "string test_broker\&.server_address = 'tcp://127\&.0\&.0\&.1:5679'"

.PP
Definition at line 13 of file test_broker\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
