.TH "test_ugly.SimpleServer" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_ugly.SimpleServer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBport\fP, \fBorigin\fP=42)"
.br
.ti -1c
.RI "def \fBdo_bot\fP (self)"
.br
.ti -1c
.RI "def \fBsend_pay\fP (self)"
.br
.ti -1c
.RI "def \fBrecv_pay\fP (self, \fBtimeout\fP=0)"
.br
.ti -1c
.RI "def \fBsend_dat\fP (self)"
.br
.ti -1c
.RI "def \fBrecv_dat\fP (self, \fBtimeout\fP=\-1)"
.br
.ti -1c
.RI "def \fBeot\fP (self, \fBtimeout\fP=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBorigin\fP"
.br
.ti -1c
.RI "\fBcredit\fP"
.br
.ti -1c
.RI "\fBdirection\fP"
.br
.ti -1c
.RI "\fBcount\fP"
.br
.ti -1c
.RI "\fBclient_id\fP"
.br
.ti -1c
.RI "\fBpoller\fP"
.br
.ti -1c
.RI "\fBis_sender\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file test_ugly\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_ugly\&.SimpleServer\&.__init__ ( self,  port,  origin = \fC42\fP)"

.PP
Definition at line 20 of file test_ugly\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_ugly\&.SimpleServer\&.do_bot ( self)"

.PP
Definition at line 30 of file test_ugly\&.py\&.
.SS "def test_ugly\&.SimpleServer\&.eot ( self,  timeout = \fC0\fP)"

.PP
Definition at line 133 of file test_ugly\&.py\&.
.SS "def test_ugly\&.SimpleServer\&.recv_dat ( self,  timeout = \fC\-1\fP)"

.PP
Definition at line 113 of file test_ugly\&.py\&.
.SS "def test_ugly\&.SimpleServer\&.recv_pay ( self,  timeout = \fC0\fP)"

.PP
Definition at line 81 of file test_ugly\&.py\&.
.SS "def test_ugly\&.SimpleServer\&.send_dat ( self)"

.PP
Definition at line 99 of file test_ugly\&.py\&.
.SS "def test_ugly\&.SimpleServer\&.send_pay ( self)"

.PP
Definition at line 67 of file test_ugly\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "test_ugly\&.SimpleServer\&.client_id"

.PP
Definition at line 26 of file test_ugly\&.py\&.
.SS "test_ugly\&.SimpleServer\&.count"

.PP
Definition at line 25 of file test_ugly\&.py\&.
.SS "test_ugly\&.SimpleServer\&.credit"

.PP
Definition at line 23 of file test_ugly\&.py\&.
.SS "test_ugly\&.SimpleServer\&.direction"

.PP
Definition at line 24 of file test_ugly\&.py\&.
.SS "test_ugly\&.SimpleServer\&.is_sender"

.PP
Definition at line 48 of file test_ugly\&.py\&.
.SS "test_ugly\&.SimpleServer\&.origin"

.PP
Definition at line 22 of file test_ugly\&.py\&.
.SS "test_ugly\&.SimpleServer\&.poller"

.PP
Definition at line 27 of file test_ugly\&.py\&.
.SS "test_ugly\&.SimpleServer\&.port"

.PP
Definition at line 21 of file test_ugly\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
