.TH "test/test_message.cpp" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_message.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/message\&.hpp'\fP
.br
\fC#include 'zio/main\&.hpp'\fP
.br
\fC#include 'zio/logging\&.hpp'\fP
.br
\fC#include <cassert>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 7 of file test_message\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
