.TH "test/test_peer.cpp" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_peer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'zio/peer\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdump_peer\fP (\fBzio::Peer\fP &peer)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dump_peer (\fBzio::Peer\fP & peer)"

.PP
Definition at line 8 of file test_peer\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 20 of file test_peer\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
