.TH "test/test_credit.cpp" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_credit.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <czmq\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHUNK_SIZE\fP   250000"
.br
.ti -1c
.RI "#define \fBPIPELINE\fP   10"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHUNK_SIZE   250000"

.PP
Definition at line 15 of file test_credit\&.cpp\&.
.SS "#define PIPELINE   10"

.PP
Definition at line 16 of file test_credit\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 129 of file test_credit\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
