.TH "python/tests/test_ugly.py" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/tests/test_ugly.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest_ugly\&.SimpleServer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest_ugly\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest_ugly\&.now\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtest_ugly\&.ctx\fP = zmq\&.Context()"
.br
.ti -1c
.RI "\fBtest_ugly\&.sock\fP = ctx\&.socket(zmq\&.SERVER)"
.br
.ti -1c
.RI "string \fBtest_ugly\&.addr\fP = 'tcp://127\&.0\&.0\&.1:5678'"
.br
.ti -1c
.RI "\fBtest_ugly\&.node\fP = pyre\&.Pyre('testflows')"
.br
.ti -1c
.RI "string \fBtest_ugly\&.portname\fP = 'recver'"
.br
.ti -1c
.RI "\fBtest_ugly\&.ss\fP = SimpleServer(sock);"
.br
.ti -1c
.RI "bool \fBtest_ugly\&.I_quit\fP = False"
.br
.ti -1c
.RI "\fBtest_ugly\&.ok\fP = ss\&.recv_dat()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
