.TH "test/test_libzmq3048.cpp" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_libzmq3048.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <unordered_set>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <zmq\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclient\fP (std::string str)"
.br
.ti -1c
.RI "void \fBserver\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void client (std::string str)"

.PP
Definition at line 16 of file test_libzmq3048\&.cpp\&.
.SS "int main (void)"

.PP
Definition at line 87 of file test_libzmq3048\&.cpp\&.
.SS "void server ()"

.PP
Definition at line 46 of file test_libzmq3048\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
