.TH "test_flowbroker.Factory" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_flowbroker.Factory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBaddress\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, bot)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhandlers\fP"
.br
.ti -1c
.RI "\fBaddress\fP"
.br
.ti -1c
.RI "\fBctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file test_flowbroker\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_flowbroker\&.Factory\&.__init__ ( self,  address)"

.PP
Definition at line 114 of file test_flowbroker\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_flowbroker\&.Factory\&.__call__ ( self,  bot)"

.PP
Definition at line 119 of file test_flowbroker\&.py\&.
.SS "def test_flowbroker\&.Factory\&.stop ( self)"

.PP
Definition at line 127 of file test_flowbroker\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "test_flowbroker\&.Factory\&.address"

.PP
Definition at line 116 of file test_flowbroker\&.py\&.
.SS "test_flowbroker\&.Factory\&.ctx"

.PP
Definition at line 117 of file test_flowbroker\&.py\&.
.SS "test_flowbroker\&.Factory\&.handlers"

.PP
Definition at line 115 of file test_flowbroker\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
