.TH "python/zio/util.py" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/zio/util.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzio\&.util\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBzio\&.util\&.needs_codec\fP (stype)"
.br
.ti -1c
.RI "def \fBzio\&.util\&.guess_hostname\fP ()"
.br
.ti -1c
.RI "def \fBzio\&.util\&.byteify_list\fP (lst)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBzio\&.util\&.socket_names\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
