.TH "zio::level" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio::level
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMessageLevel\fP { \fBundefined\fP =0, \fBtrace\fP, \fBverbose\fP, \fBdebug\fP, \fBinfo\fP, \fBsummary\fP, \fBwarning\fP, \fBerror\fP, \fBfatal\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBname\fP (\fBMessageLevel\fP lvl)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBzio::level::MessageLevel\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIundefined \fP\fP
.TP
\fB\fItrace \fP\fP
.TP
\fB\fIverbose \fP\fP
.TP
\fB\fIdebug \fP\fP
.TP
\fB\fIinfo \fP\fP
.TP
\fB\fIsummary \fP\fP
.TP
\fB\fIwarning \fP\fP
.TP
\fB\fIerror \fP\fP
.TP
\fB\fIfatal \fP\fP
.PP
Definition at line 18 of file message\&.hpp\&.
.SH "Function Documentation"
.PP 
.SS "const char * zio::level::name (\fBMessageLevel\fP lvl)"

.PP
Definition at line 7 of file message\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
