.TH "zio.flow.util" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.flow.util
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBobjectify\fP (morl)"
.br
.ti -1c
.RI "def \fBstringify\fP (flowtype, params)"
.br
.ti -1c
.RI "def \fBswitch_direction\fP (fobj)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def zio\&.flow\&.util\&.objectify ( morl)"

.PP
.nf
Return a flow object.

The morl may be a zio.Message or a zio.Message.label

.fi
.PP
 
.PP
Definition at line 5 of file util\&.py\&.
.SS "def zio\&.flow\&.util\&.stringify ( flowtype,  params)"

.PP
.nf
Return a flow label string of given flow type and any extra
parameters.

.fi
.PP
 
.PP
Definition at line 19 of file util\&.py\&.
.SS "def zio\&.flow\&.util\&.switch_direction ( fobj)"

.PP
Definition at line 29 of file util\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
