.TH "zio.message.MessageLevel" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.message.MessageLevel
.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBundefined\fP = 0"
.br
.ti -1c
.RI "int \fBtrace\fP = 1"
.br
.ti -1c
.RI "int \fBverbose\fP = 2"
.br
.ti -1c
.RI "int \fBdebug\fP = 3"
.br
.ti -1c
.RI "int \fBinfo\fP = 4"
.br
.ti -1c
.RI "int \fBsummary\fP = 5"
.br
.ti -1c
.RI "int \fBwarning\fP = 6"
.br
.ti -1c
.RI "int \fBerror\fP = 7"
.br
.ti -1c
.RI "int \fBfatal\fP = 8"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file message\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "int zio\&.message\&.MessageLevel\&.debug = 3\fC [static]\fP"

.PP
Definition at line 16 of file message\&.py\&.
.SS "int zio\&.message\&.MessageLevel\&.error = 7\fC [static]\fP"

.PP
Definition at line 20 of file message\&.py\&.
.SS "int zio\&.message\&.MessageLevel\&.fatal = 8\fC [static]\fP"

.PP
Definition at line 21 of file message\&.py\&.
.SS "int zio\&.message\&.MessageLevel\&.info = 4\fC [static]\fP"

.PP
Definition at line 17 of file message\&.py\&.
.SS "int zio\&.message\&.MessageLevel\&.summary = 5\fC [static]\fP"

.PP
Definition at line 18 of file message\&.py\&.
.SS "int zio\&.message\&.MessageLevel\&.trace = 1\fC [static]\fP"

.PP
Definition at line 14 of file message\&.py\&.
.SS "int zio\&.message\&.MessageLevel\&.undefined = 0\fC [static]\fP"

.PP
Definition at line 13 of file message\&.py\&.
.SS "int zio\&.message\&.MessageLevel\&.verbose = 2\fC [static]\fP"

.PP
Definition at line 15 of file message\&.py\&.
.SS "int zio\&.message\&.MessageLevel\&.warning = 6\fC [static]\fP"

.PP
Definition at line 19 of file message\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
