.TH "zio::peer_info_t" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio::peer_info_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <peer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBheaderset_t\fP \fBbranch\fP (const std::string &prefix)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnickname_t\fP \fBnick\fP {''}"
.br
.ti -1c
.RI "\fBheaderset_t\fP \fBheaders\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file peer\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBzio::headerset_t\fP zio::peer_info_t::branch (const std::string & prefix)"

.PP
Definition at line 4 of file peer\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBheaderset_t\fP zio::peer_info_t::headers"

.PP
Definition at line 26 of file peer\&.hpp\&.
.SS "\fBnickname_t\fP zio::peer_info_t::nick {''}"

.PP
Definition at line 25 of file peer\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
