.TH "zio::CoordHeader" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio::CoordHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <message\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBorigin_t\fP \fBorigin\fP {0}"
.br
.ti -1c
.RI "\fBgranule_t\fP \fBgranule\fP {0}"
.br
.ti -1c
.RI "\fBseqno_t\fP \fBseqno\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file message\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBgranule_t\fP zio::CoordHeader::granule {0}"

.PP
Definition at line 42 of file message\&.hpp\&.
.SS "\fBorigin_t\fP zio::CoordHeader::origin {0}"

.PP
Definition at line 41 of file message\&.hpp\&.
.SS "\fBseqno_t\fP zio::CoordHeader::seqno {0}"

.PP
Definition at line 43 of file message\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
