.TH "zio.peer" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.peer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPeer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlog\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fBPeerInfo\fP = namedtuple('PeerInfo','uuid nick headers')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
ZIO peering

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "zio\&.peer\&.log = logging\&.getLogger(__name__)"

.PP
Definition at line 13 of file peer\&.py\&.
.SS "zio\&.peer\&.PeerInfo = namedtuple('PeerInfo','uuid nick headers')"

.PP
Definition at line 14 of file peer\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
