.TH "zio::Header" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio::Header
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <message\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPrefixHeader\fP \fBprefix\fP"
.br
.ti -1c
.RI "\fBCoordHeader\fP \fBcoord\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file message\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCoordHeader\fP zio::Header::coord"

.PP
Definition at line 47 of file message\&.hpp\&.
.SS "\fBPrefixHeader\fP zio::Header::prefix"

.PP
Definition at line 46 of file message\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
