.TH "zio::PrefixHeader" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio::PrefixHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <message\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBdumps\fP () const"
.br
.ti -1c
.RI "bool \fBloads\fP (const std::string &s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlevel::MessageLevel\fP \fBlevel\fP {\fBlevel::undefined\fP}"
.br
.ti -1c
.RI "std::string \fBform\fP {' '}"
.br
.ti -1c
.RI "std::string \fBlabel\fP {''}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file message\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string zio::PrefixHeader::dumps () const"

.PP
Definition at line 20 of file message\&.cpp\&.
.SS "bool zio::PrefixHeader::loads (const std::string & s)"

.PP
Definition at line 31 of file message\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string zio::PrefixHeader::form {' '}"

.PP
Definition at line 28 of file message\&.hpp\&.
.SS "std::string zio::PrefixHeader::label {''}"

.PP
Definition at line 29 of file message\&.hpp\&.
.SS "\fBlevel::MessageLevel\fP zio::PrefixHeader::level {\fBlevel::undefined\fP}"

.PP
Definition at line 27 of file message\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
