.TH "zio.flow.broker" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.flow.broker
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBroker\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlog\fP = logging\&.getLogger('zpb')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
ZIO brokers bring together ZIO clients.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "zio\&.flow\&.broker\&.log = logging\&.getLogger('zpb')"

.PP
Definition at line 13 of file broker\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
