.TH "zio.flow.proto" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.flow.proto
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirection\fP"
.br
.ti -1c
.RI "class \fBFlow\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlog\fP = logging\&.getLogger('zpb')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
zio.flow implements ZIO flow protocol helper

This is equivalent to the C++ zio::flow namespace

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "zio\&.flow\&.proto\&.log = logging\&.getLogger('zpb')"

.PP
Definition at line 13 of file proto\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
