.TH "zio.__main__" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.__main__
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlevel\fP"
.br
.ti -1c
.RI "\fBformat\fP"
.br
.ti -1c
.RI "\fBdatefmt\fP"
.br
.ti -1c
.RI "\fBlog\fP = logging\&.getLogger('zio')"
.br
.ti -1c
.RI "\fBcli\fP = click\&.CommandCollection(sources=[peers\&.cli, flow\&.cli, domo\&.cli])"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Main CLI to ZIO 

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def zio\&.__main__\&.main (void)"

.PP
Definition at line 16 of file __main__\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "zio\&.__main__\&.cli = click\&.CommandCollection(sources=[peers\&.cli, flow\&.cli, domo\&.cli])"

.PP
Definition at line 14 of file __main__\&.py\&.
.SS "zio\&.__main__\&.datefmt"

.PP
Definition at line 10 of file __main__\&.py\&.
.SS "zio\&.__main__\&.format"

.PP
Definition at line 9 of file __main__\&.py\&.
.SS "zio\&.__main__\&.level"

.PP
Definition at line 8 of file __main__\&.py\&.
.SS "zio\&.__main__\&.log = logging\&.getLogger('zio')"

.PP
Definition at line 11 of file __main__\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
