.TH "zio.port" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.port
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPort\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBbind_address\fP (sock, \fBaddr\fP)"
.br
.ti -1c
.RI "def \fBbind_hostport\fP (sock, host, port)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBephemeral_port_range\fP = (49152, 65535)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def zio\&.port\&.bind_address ( sock,  addr)"

.PP
.nf
Bind socket to address

Any error is printed and reraised.

:param sock: ZeroMQ socket object
:param addr: address in ZeroMQ format
:returns: the address
:rtype: string
.fi
.PP
 
.PP
Definition at line 8 of file port\&.py\&.
.SS "def zio\&.port\&.bind_hostport ( sock,  host,  port)"

.PP
.nf
Bind socket TCP host and port

:param sock: ZeroMQ socket object
:param host: name or IP address of host to bind
:param port: TCP port number
:returns: ZeroMQ address string
:rtype: string
.fi
.PP
 
.PP
Definition at line 29 of file port\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple zio\&.port\&.ephemeral_port_range = (49152, 65535)"

.PP
Definition at line 27 of file port\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
