.TH "zio::Node" 3 "Fri Jan 3 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio::Node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <node\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (\fBnickname_t\fP \fBnick\fP='', \fBorigin_t\fP \fBorigin\fP=0, const std::string &hostname='')"
.br
.ti -1c
.RI "\fB~Node\fP ()"
.br
.ti -1c
.RI "\fBnickname_t\fP \fBnick\fP () const"
.br
.ti -1c
.RI "\fBorigin_t\fP \fBorigin\fP () const"
.br
.ti -1c
.RI "const std::vector< std::string > & \fBportnames\fP () const"
.br
.ti -1c
.RI "void \fBset_nick\fP (const \fBnickname_t\fP &\fBnick\fP)"
.br
.ti -1c
.RI "void \fBset_origin\fP (\fBorigin_t\fP \fBorigin\fP)"
.br
.ti -1c
.RI "void \fBset_verbose\fP (bool \fBverbose\fP=true)"
.br
.ti -1c
.RI "bool \fBverbose\fP () const"
.br
.ti -1c
.RI "\fBportptr_t\fP \fBport\fP (const std::string &name, int stype)"
.br
.ti -1c
.RI "\fBportptr_t\fP \fBport\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBonline\fP (const \fBheaderset_t\fP &extra_headers={})"
.br
.ti -1c
.RI "void \fBoffline\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file node\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "zio::Node::Node (\fBnickname_t\fP nick = \fC''\fP, \fBorigin_t\fP origin = \fC0\fP, const std::string & hostname = \fC''\fP)"

.PP
Definition at line 18 of file node\&.cpp\&.
.SS "zio::Node::~Node ()"

.PP
Definition at line 30 of file node\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBnickname_t\fP zio::Node::nick () const\fC [inline]\fP"

.PP
Definition at line 45 of file node\&.hpp\&.
.SS "void zio::Node::offline ()"

.PP
Definition at line 79 of file node\&.cpp\&.
.SS "void zio::Node::online (const \fBheaderset_t\fP & extra_headers = \fC{}\fP)"

.PP
Definition at line 58 of file node\&.cpp\&.
.SS "\fBorigin_t\fP zio::Node::origin () const\fC [inline]\fP"

.PP
Definition at line 46 of file node\&.hpp\&.
.SS "\fBzio::portptr_t\fP zio::Node::port (const std::string & name, int stype)"

.PP
Definition at line 36 of file node\&.cpp\&.
.SS "\fBzio::portptr_t\fP zio::Node::port (const std::string & name)"

.PP
Definition at line 48 of file node\&.cpp\&.
.SS "const std::vector<std::string>& zio::Node::portnames () const\fC [inline]\fP"

.PP
Definition at line 47 of file node\&.hpp\&.
.SS "void zio::Node::set_nick (const \fBnickname_t\fP & nick)\fC [inline]\fP"

.PP
Definition at line 51 of file node\&.hpp\&.
.SS "void zio::Node::set_origin (\fBorigin_t\fP origin)"

.PP
Definition at line 90 of file node\&.cpp\&.
.SS "void zio::Node::set_verbose (bool verbose = \fCtrue\fP)"

.PP
Definition at line 97 of file node\&.cpp\&.
.SS "bool zio::Node::verbose () const\fC [inline]\fP"

.PP
Definition at line 56 of file node\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
