.TH "zio.flow.example_handler" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.flow.example_handler
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFactory\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBhandshake\fP (pipe, flow, bot)"
.br
.ti -1c
.RI "def \fBdump_actor\fP (ctx, pipe, flow, bot, args)"
.br
.ti -1c
.RI "def \fBgen_actor\fP (ctx, pipe, flow, bot, args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Example of handlers spawned from backend.spawner

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def zio\&.flow\&.example_handler\&.dump_actor ( ctx,  pipe,  flow,  bot,  args)"

.PP
.nf
Dump flow messages

.fi
.PP
 
.PP
Definition at line 19 of file example_handler\&.py\&.
.SS "def zio\&.flow\&.example_handler\&.gen_actor ( ctx,  pipe,  flow,  bot,  args)"

.PP
.nf
Generate flow messages

.fi
.PP
 
.PP
Definition at line 37 of file example_handler\&.py\&.
.SS "def zio\&.flow\&.example_handler\&.handshake ( pipe,  flow,  bot)"

.PP
Definition at line 13 of file example_handler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
