.TH "zio.flow.proto.Direction" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.flow.proto.Direction
.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBundefined\fP = 0"
.br
.ti -1c
.RI "int \fBextract\fP = 1"
.br
.ti -1c
.RI "int \fBinject\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file proto\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "int zio\&.flow\&.proto\&.Direction\&.extract = 1\fC [static]\fP"

.PP
Definition at line 18 of file proto\&.py\&.
.SS "int zio\&.flow\&.proto\&.Direction\&.inject = 2\fC [static]\fP"

.PP
Definition at line 19 of file proto\&.py\&.
.SS "int zio\&.flow\&.proto\&.Direction\&.undefined = 0\fC [static]\fP"

.PP
Definition at line 17 of file proto\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
