.TH "zio.message.CoordHeader" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.message.CoordHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, args, \fBorigin\fP=0, \fBgranule\fP=0, \fBseqno\fP=0)"
.br
.ti -1c
.RI "def \fB__bytes__\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBorigin\fP"
.br
.ti -1c
.RI "\fBgranule\fP"
.br
.ti -1c
.RI "\fBseqno\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBorigin\fP = 0"
.br
.ti -1c
.RI "int \fBgranule\fP = 0"
.br
.ti -1c
.RI "int \fBseqno\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file message\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def zio\&.message\&.CoordHeader\&.__init__ ( self,  args,  origin = \fC0\fP,  granule = \fC0\fP,  seqno = \fC0\fP)"

.PP
Definition at line 87 of file message\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def zio\&.message\&.CoordHeader\&.__bytes__ ( self)"

.PP
Definition at line 100 of file message\&.py\&.
.SS "def zio\&.message\&.CoordHeader\&.__repr__ ( self)"

.PP
Definition at line 106 of file message\&.py\&.
.SS "def zio\&.message\&.CoordHeader\&.__str__ ( self)"

.PP
Definition at line 103 of file message\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "int zio\&.message\&.CoordHeader\&.granule = 0\fC [static]\fP"

.PP
Definition at line 84 of file message\&.py\&.
.SS "zio\&.message\&.CoordHeader\&.granule"

.PP
Definition at line 89 of file message\&.py\&.
.SS "int zio\&.message\&.CoordHeader\&.origin = 0\fC [static]\fP"

.PP
Definition at line 83 of file message\&.py\&.
.SS "zio\&.message\&.CoordHeader\&.origin"

.PP
Definition at line 88 of file message\&.py\&.
.SS "int zio\&.message\&.CoordHeader\&.seqno = 0\fC [static]\fP"

.PP
Definition at line 85 of file message\&.py\&.
.SS "zio\&.message\&.CoordHeader\&.seqno"

.PP
Definition at line 90 of file message\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
