.TH "zio::flow" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio::flow \- ZIO data flow\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbroker\fP"
.br
.ti -1c
.RI " \fBexample_handler\fP"
.br
.ti -1c
.RI " \fBfactories\fP"
.br
.ti -1c
.RI " \fBhdf\fP"
.br
.ti -1c
.RI " \fBproto\fP"
.br
.ti -1c
.RI " \fButil\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFlow\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDirection\fP { \fBundefined\fP, \fBextract\fP, \fBinject\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
ZIO data flow\&. 


.PP
.nf
Python implementation of ZIO flow bits

.fi
.PP
 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBzio::flow::Direction\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIundefined \fP\fP
.TP
\fB\fIextract \fP\fP
.TP
\fB\fIinject \fP\fP
.PP
Definition at line 18 of file flow\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
