.TH "zio.__main__" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zio.__main__
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcli\fP (ctx)"
.br
.ti -1c
.RI "def \fBpeers\fP (\fBtimeout\fP, wait_for, pre_sleep, post_sleep, name, headers)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Main CLI to ZIO 

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def zio\&.__main__\&.cli ( ctx)"

.PP
.nf
ZIO command line interface

.fi
.PP
 
.PP
Definition at line 14 of file __main__\&.py\&.
.SS "def zio\&.__main__\&.main (void)"

.PP
Definition at line 56 of file __main__\&.py\&.
.SS "def zio\&.__main__\&.peers ( timeout,  wait_for,  pre_sleep,  post_sleep,  name,  headers)"

.PP
.nf
Join Zyre and discover peers.

.fi
.PP
 
.PP
Definition at line 31 of file __main__\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
