.TH "zmq::socket_ref" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zmq::socket_ref
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zmq\&.hpp>\fP
.PP
Inherits \fBzmq::detail::socket_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsocket_ref\fP () \fBZMQ_NOTHROW\fP"
.br
.ti -1c
.RI "\fBsocket_ref\fP (\fBfrom_handle_t\fP, void *handle) \fBZMQ_NOTHROW\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1547 of file zmq\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "zmq::socket_ref::socket_ref ()\fC [inline]\fP"

.PP
Definition at line 1550 of file zmq\&.hpp\&.
.SS "zmq::socket_ref::socket_ref (\fBfrom_handle_t\fP, void * handle)\fC [inline]\fP"

.PP
Definition at line 1554 of file zmq\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
