.TH "zmq::error_t" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zmq::error_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zmq\&.hpp>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBerror_t\fP ()"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const \fBZMQ_NOTHROW\fP \fBZMQ_OVERRIDE\fP"
.br
.ti -1c
.RI "int \fBnum\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 237 of file zmq\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "zmq::error_t::error_t ()\fC [inline]\fP"

.PP
Definition at line 240 of file zmq\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int zmq::error_t::num () const\fC [inline]\fP"

.PP
Definition at line 242 of file zmq\&.hpp\&.
.SS "virtual const char* zmq::error_t::what () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 241 of file zmq\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
