.TH "zmq_event_t" 3 "Tue Feb 4 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zmq_event_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zmq\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBevent\fP"
.br
.ti -1c
.RI "int32_t \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file zmq\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t zmq_event_t::event"

.PP
Definition at line 164 of file zmq\&.hpp\&.
.SS "int32_t zmq_event_t::value"

.PP
Definition at line 165 of file zmq\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
