.TH "zmq::from_handle_t" 3 "Wed Mar 18 2020" "ZIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zmq::from_handle_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zmq\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_private\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZMQ_CONSTEXPR_FN\fP \fBZMQ_EXPLICIT\fP \fBfrom_handle_t\fP (\fB_private\fP) \fBZMQ_NOTHROW\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1534 of file zmq\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBZMQ_CONSTEXPR_FN\fP \fBZMQ_EXPLICIT\fP zmq::from_handle_t::from_handle_t (\fB_private\fP)\fC [inline]\fP"

.PP
Definition at line 1539 of file zmq\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ZIO from the source code\&.
