#+title: ZIO

* Introduction

ZIO provides a thin, simplifying wrapper around ZeroMQ's CZMQ and
Zyre.  It provides:

- a general, container-based transport of data in a few convenient message formats.

- a simplified discovery and presence mechanism based on Zyre.

- some general purpose functionality for processing ZIO messages.

The goal of ZIO is to form the basis for a loosely coupled ecosystem
of libraries and applications which can inter-communicate.  Some
anticipated uses are:

- Wire-Cell Toolkit I/O requires accepting data from multi-threaded
  contexts, aggregating it to a single thread and writing to one or
  several file formats.  Reading requires the reverse, bringing data
  back to WCT component threads for replay.

- Software self-trigger feature for DUNE DAQ (or others) require
  streamed data processing to aggregate and locate "interesting"
  portions of an original data stream.

- Logging and structured metric production, processing and collection
  from a distributed system.

* Install

#+begin_example
  $ waf configure --prefix=/path/to/install
  $ waf build [--notests]
  $ [waf build --alltests]
  $ waf install
#+end_example

* More information

- [[file:docs/messages.org]] describes the ZIO message format

- [[file:docs/batteries.org]] describes additional features ~libzio~ provides

- [[file:docs/misc.org]] holds some uncategorized ramblings
