@startuml
package "Broader Wire-Cell Graph" {
        [Some Producers] as prod
        [Some Consumers] as cons
}


package "Wire-Cell IData" {
        storage "ITensorSet" as tensors
}
package "Wire-Cell/ZIO Converts" {
        [ZioTensorSink]
        [ZioTensorSource]
        [ZioGpuClient]
}
cloud "ZIO Message Transfer\n" {
        queue "flow queue\nFLOW/TENS msg" as flow
        queue "domo queue\nTENS msg" as work
}
package "ZIO Brokers, handlers, workers" {
        [Flow Broker] as flowb
        [Domo Broker] as domob
        [HDF Reader] as hdfr
        [HDF Writer] as hdfw
        [GPU Worker] as gpuw

        flow <--> flowb
        flowb --> hdfw
        flowb <-- hdfr

        work <--> domob
        domob <--> gpuw
} 
package "Resources" {
        database HDF5 as hdf
        frame GPU
}        
prod --> tensors
cons <-- tensors

tensors --> [ZioTensorSink]
tensors <-- [ZioTensorSource]
[ZioTensorSink] --> flow
[ZioTensorSource] <-- flow
[ZioGpuClient] <--> work
tensors <--> [ZioGpuClient]
hdfr <-- hdf
hdfw --> hdf
gpuw <--> GPU
@enduml
