@startuml
title Extract data


activate server
server -> server: BIND
note left
        client or server may
        bind or connect,
end note
activate client
client -> server : CONNECT

group initiate

client -> server : REQ (2 creds)

note left
        client extends
        credit to server.
end note

server --> client : PAY (2)
note left
        client knows
        server is ready
end note

end

group transfer

client -> server : data(BOS)
server --> client : PAY (1)
client -> server : data(PL)
server --> client : PAY (2)
client -> server : data(PL)
client -> server : data(PL)
server --> client : PAY (2)
client -> server : data(EOS)
server --> client : PAY (1)
client -> client : handle EOS 
note left
Transmission may continue.
end note
client -> server : data(BOS)
client -> server : data(PL)
server --> client : PAY (2)
client -> server : data(EOS)
server --> client : PAY (1)
client -> client : handle EOS 
end

group finalize
client -> server : EOT
note left
client indicates
end of data.
end note
server --> client : PAY (1)
client -> client : handle EOT
note left
client not longer recv()
end note
end

destroy client

@enduml
