@startuml
left to right direction
title ZIO data flow states
[*] --> CTOR : construct
CTOR --> WANTBOT : send_bot
CTOR --> OWEBOT : recv_bot
WANTBOT --> INI : recv_bot
OWEBOT --> INI : send_bot

INI --> EXTRACTING : [direction=extract]
INI --> INJECTING : [direction=inject]

EXTRACTING -> EXTRACTING : send_dat
EXTRACTING -> EXTRACTING : recv_pay [msg={PAY,timout}]
EXTRACTING -> EXTRACTING : recv_pay [msg=???] / drop
EXTRACTING --> FINACK : recv_pay [msg=EOT]
EXTRACTING --> ACKFIN : send_eot

INJECTING -> INJECTING : send_pay
INJECTING -> INJECTING : recv_dat [msg={DAT,timeout}]
INJECTING -> INJECTING : recv_dat [msg=???] / drop
INJECTING --> FINACK : recv_dat [msg=EOT]
INJECTING --> ACKFIN : send_eot

FINACK --> FIN : send_eot
ACKFIN --> FIN : recv_eot

@enduml
