@startuml
title Inject data from server to client
activate server
        server -> server: BIND
        activate client
                client -> server : CONNECT
                group initiate
                        client -> server : BOT
                        note left
                                direction
                        end note
                        server -> client : BOT
                        note right
                                credits (eg 2)
                        end note
                end
                group transfer (inject)
                        server  -> client : DAT
                        note left
                                1 cred
                        end note
                        client --> server : PAY (1)
                        note left
                                2 cred
                        end note
                        server  -> client : DAT
                        server  -> client : DAT
                        client --> server : PAY (2)
                        server  -> client : DAT
                        client --> server : PAY (1)
                        server  -> client : DAT
                        server  -> client : DAT
                        server -> client : EOT
                        client --> server : PAY (2)
                        client --> server : EOT
                end
                destroy client
                @enduml
