@startuml
!pragma teoz true

title ZIO Flow Broker Sequence
participant "client" as client
participant "port" as feport
participant "broker" as broker
participant "handler" as app
participant "factory" as factory

broker -> feport : recv(wait)
client -> feport : BOT-rem
& feport -> broker : BOT-rem
broker -> factory : call(BOT-loc+cid)
factory -> app : spawn handler
activate app
        app -> feport : BOT-loc+cid
        feport -> broker : BOT-loc+cid
        broker -> feport 
        & feport -> client : BOT-loc
        broker -> feport : BOT-rem
        feport -> app  : BOT-rem
        
        client <-> feport
        & feport <-> app : PAY/DAT/EOT
        & broker <-> feport

deactivate app

@enduml
