@startuml
left to right direction
title ZIO data flow states
[*] -> CTOR : construct
CTOR -> IDLE
IDLE --> BOTSEND : SendBOT
IDLE --> BOTRECV : RecvBOT
BOTSEND --> READY : RecvBOT
BOTRECV --> READY : SendBOT

state READY {
        [*] --> GIVING : BeginFlow [is_giver]
        [*] --> TAKING : BeginFlow [!is_giver] / flush_pay

state GIVING {
        [*] --> BROKE
        BROKE -> GENEROUS : RecvPAY [ check_pay ] / recv_pay
        GENEROUS -> CREDITCHECK : SendDAT / (send_msg,process(CreditCheck))
        CREDITCHECK --> GENEROUS : CreditCheck [ have_credit ]
        CREDITCHECK --> BROKE : CreditCheck [ !have_credit ]
}

state TAKING {
        [*] --> WALLETCHECK
        WALLETCHECK -> HANDSOUT : SendPAY [ have_credit ] / flush_pay
        HANDSOUT --> WALLETCHECK : RecvDAT [ check_dat ] / (recv_msg, process(SendPAY))
}
}
READY --> FINACK : RecvEOT
READY --> ACKFIN : SendEOT

FINACK --> FIN : SendEOT
ACKFIN --> FIN : RecvEOT

@enduml
