@startuml
title Extract data from client to server
activate server
        server -> server: BIND
        activate client
                client -> server : CONNECT
                group initiate
                        client -> server : BOT
                        note left
                                direction
                        end note
                        server -> client : BOT
                        note right
                                credits (eg 2)
                        end note
                end
                group transfer (extract)
                        client  -> server : DAT
                        note right
                                1 cred
                        end note
                        server --> client : PAY (1)
                        note right
                                2 cred
                        end note
                        client  -> server : DAT
                        client  -> server : DAT
                        server --> client : PAY (2)
                        client  -> server : DAT
                        server --> client : PAY (1)
                        client  -> server : DAT
                        client  -> server : DAT
                        client -> server : EOT
                        server --> client : PAY (2)
                        server --> client : EOT
                end
                destroy client
                @enduml
