#+title: ZIO Installation
#+setupfile: setup.org
#+include: nav.org

* Install ZIO

ZIO installs in the usual [[https://waf.io][Waf]] way.

#+begin_example
  $ ./waf configure --prefix=/path/to/install
  $ ./waf install
#+end_example

To build, these software dependencies will be located via [[https://www.freedesktop.org/wiki/Software/pkg-config/][pkg-config]].

- [[https://github.com/zeromq/libzmq][libzmq]] (with draft sockets built)
- [[https://github.com/zeromq/czmq][CZMQ]]
- [[https://github.com/zeromq/zyre][Zyre]]

In addition, ZIO uses [[https://github.com/zeromq/cppzmq][cppzmq]] and [[https://github.com/nlohmann/json][nlohmann/json]] and includes copies of
these header-only packages.

* Tests

The default install target will compile and execute units tests.  To
avoid running these tests you may add ~--notests~ as:

#+begin_example
  $ ./waf install --notests
#+end_example

Or, to force their running:

#+begin_export 
  $ ./waf --alltests
#+end_export

* Documentation

The generated documentation committed to the repository.  With a
suitable environment (need Emacs and a recent [[https://plantuml.com/][plantuml]]) one can
rebuild it:

#+begin_example
  $ cd docs
  $ make
#+end_example
* Python 

ZIO also provides a Python package.  As draft sockets are needed some
special installation is required to enable them and to build PyZMQ
against the libzmq with them also enabled.

#+begin_example
  $ python3 -m venv /path/to/venv
  $ source /path/to/venv/bin/activate
  $ cd zio/python
  $ pip install --pre pyzmq \
      --install-option=--enable-drafts \
      --install-option=--zmq=/path/to/zmq
  $ pip install .
#+end_example

Replace ~/path/to~ with suitable paths.

